#!/usr/bin/bash

set -ex

themes="stackoverflow-es stackoverflow orbit orbit-original eloquent kards caffeine foxyboxy stackoverflow-skills onepage-ds shorter-miles a11y stackoverflow2 paper-plus-plus material moon material-moon spartanbentekkie curzy gross austerity pring cards saf flat-extended extelegant robin blue light-classy-responsive-m2 dark-classy-responsive spartan light-classy-concise contempo onepageresume-alt boilerplate-test compact-extended flat-zh-fork mu paper-fixed shorter-bill onepage ceevee theme-class slick spartan-skills-de intern direct compact compact-pt-br simple-red skills paper dark-classy-edit short-remix materialize spartacus-prime paper-it m4r5 joomla-flats boilerplate markdown paper-condensed papier spartacus retro srt slick-bentley ifyoumakeit slicker plick spartan-skills spartacus-nl paper-responsive onepage-efficient onepage-fr onepage-year concise-serif paper-zh-hant paper_cn minimal simplistic fizz shorter cvstrap flatphill depassementdepile haosio slick-nl onepage-pt-br short-newmanrsfork striking kate paper_en flat awolden class sergio srt-epost trivento clean fr_flat business-card flat-custom-trimed elegant-leonth compactbr simple print srt-it sshorter short onepage_zena paper-monofont ankurclass resu concise fresh paper-pt-br onepage-fork zurb onepage-nderkach onepageresumefixed json flat-davidgwking flat-optimized flat_projects rhinebeck toko boldstatement uppsala crisp business student-onepage flatter juno flat-nl donkeymedia aaron edify juno-nl modern-freelance morki minimalism flat-yi heavypaper newflat futura responsive business-card-minimal futura-wp riga flat-projects flat-fork onepageresume flat-es dangerflat flat-year tokyo wraypro modern2 elegant-zh-hant real elegant-fr-mod bootstrap-icons genocation elegantprofile ace kendalles modern-with-projects-section kwan-fix wb-elegant kwann-nl crispy-potato papirus keloran-fr nameme kendall-fork classy elegant-tautologistics qlh elegant-fr2 jat timeline-fixed refined sasha_fixed light polymer kendall-fix kendall-alt kendall-pt-br simple-nl elegant-fr elegant_sargefork kwan-nl elegant-ryantrinkle sasha ah3nry elegant-tarq verbum keloran elite cora light-classy-responsive-fr modern class2 ozee31 elegant-simplified sceptile kendall-plus light-classy-responsive elegantnew kwaln-nl elegant-hitesh timeline elegant_sargefork_no_volunteer light-caffienated tils nominaltech-nl kwam-nl kendall hydejack simplyelegant elegant-custom elegant modern-spbrien elegant-wso elegantfixed modern-extended kwan smart kendall-beardtree eddywashere sheerun printclassy nominaltech classy-fr elegant-projects briefstrap kwan-no-skills-level elegant_sargefork-no-volunteer kendall-variation semantic-ui elegant-mobile dave elegant_fork elegant-tautologistics-ptbr elegant-compact elegant-mobile-jjlorenzo dark-classy jjlorenzoelegant eleganto light-nl lemonlabs rocketspacer"
mkdir -p pdf html
for theme in $themes; do
  echo "Exporting $theme"
  node_modules/.bin/resume export --theme $theme pdf/resume-$theme.pdf
  node_modules/.bin/resume export --theme $theme html/resume-$theme.html
done
